# Gathering the data

## Initilize the setups

In [7]:
import numpy as np
import pandas as pd

In [8]:
# prompt: generate the code to change the current working directory to main directory

import os
# Check the current working directory
print(os.getcwd())

# List contents of the main directory (root directory)
!ls

# Change the current working directory
os.chdir('/content/drive/MyDrive/Colab Notebooks/Complete Machine Learning/Gathering the Data') # Write the current working directory as parameter

/content/drive/MyDrive/Colab Notebooks/Complete Machine Learning/Gathering the Data
 aug_train.csv		      'IPL Matches 2008-2020.csv'   test.csv
 BX-Books.csv		       movie_titles_metadata.tsv    zomato.csv
'Gathering the data 1.ipynb'   Recipe_train.json

# Working with CSV, TSV
CSV stand for Comma seperated values.  
TSV stand for tab seperated values.  

Panda Documentation link: [Pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

## Opening a local file

In [9]:
df = pd.read_csv('aug_train.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
# Without seperation
movie_df=pd.read_csv('movie_titles_metadata.tsv')
movie_df
# In case of TSV file we have to specify the seperate parameter using sep='/t'

## Fetching Data from URL

In [ ]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv" #Just change the URL to Required one
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

#This programe will work as Clint and Visit the URL

## Seperate TSV data
In case of TSV file we have to specify the seperate parameter using  
```pd.read_csv(FILE_NAME.TSV, sep='/t')```

In [ ]:
# With seperation
movie_df=pd.read_csv('movie_titles_metadata.tsv',sep='\t')
movie_df.head()

# In this case we don't have name of collumn then it will automatically take first row as name of column

## Name
In case we dont have the name row for the columns then we will pass it through `name` parameter. And we have to pass the <U> list </U>

In [ ]:
# Now passing the list of name of columns as follows
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

## Index-col paramenter
In the case when the data contain two ID column, Or the some unusable unique column. then change the main index of numbers to that specifix column.    
eg: Train data set contain both enrollee_id as well as index. So insted of keeping two index change the main indes to enrollee_id.

In [ ]:
pd.read_csv('aug_train.csv')
# Here there is two id and one extra collumn is there which is representing the each rows.
# So we change the main sr_no collumn with entollee_ID

In [ ]:
pd.read_csv('aug_train.csv',index_col='enrollee_id')

## Header parameter
Due to some mistake in dataset, the name of column is considered as first row.
Then we use header parameter.

In [ ]:
# Printing the dataset having the name of column in first row
pd.read_csv('test.csv')

In [ ]:
# Using the header parameter to set the column name to row 1st.
pd.read_csv('test.csv',header=1, index_col='0') # Also rewrite the data with arranged indexing

## use_cols parameters
In the case when we have to use only 2-3 collumn of some dataset. Then we use the parameter ``` usecols = ['', '' ...] ``` .

In [ ]:
pd.read_csv('aug_train.csv')

In [ ]:
# Acessing the data of some column only
pd.read_csv('aug_train.csv', usecols=['enrollee_id', 'city', 'gender', 'experience'])

## Skiprows/nrows Parameter
**skiprows:** If we don't want any perticular row in our dataset then we can use Skilrow parameter.  
> To remove some row y any conditions

**nrows:** Similarly if we want only n numbers of row then we use nrows parameter.  
> As we have large amount of data then we use n rows to import small chunk of data.

In [ ]:
pd.read_csv('aug_train.csv',skiprows=[1,2])

In [ ]:
# Getting first 100 data as one chunk
pd.read_csv('aug_train.csv',nrows=100)

## Encoding parameter
In some dataset the encoding is unique and we have to change its encoding to deal such dataset using this parameter.

In [ ]:
pd.read_csv('zomato.csv') # Here in this dataset the encoding is different so we have to change it first

In [ ]:
pd.read_csv('zomato.csv', encoding='latin-1') # Acessed the data by changing the default endoding to 'latin-1'

## Skip bad lines
It refers to when a row contain values more than number of column.

In [ ]:
pd.read_csv("BX-Books.csv", sep = ";")

In [ ]:
pd.read_csv("BX-Books.csv", sep = ";", encoding= "latin-1", on_bad_lines='skip')

## Dtype
Most of the dataset contain unnecessary larger datatype. Or if we require to change the datatype of data while fetching the use dtype and pass dictionary as value.

In [ ]:
# Here in this dataset the last column "Target" is written in float datatype
df=pd.read_csv('aug_train.csv') # Whereas the values in "Target" column is in int type
df

In [ ]:
# Getting the information about dataset before changing the datatype
print(df.info())
print("*"*50,"\n")

# Getting the infornation about dataset after changing the datatype
print(pd.read_csv('aug_train.csv',dtype={'target':int}).info()," \n\n Data set: \n")
df

## Handling Dates
Dates column in dataset generally considered as string, But to deal with dates dataset we can change it using : ```parse_dates=[date]```

---
Note
* If we want to pass multipal column then we can just pass the index of that column as `list`.
* If we have a dataset having dates, Month, Year in different column then we can pass `list of list` for such cases.

In [ ]:
# In this dataset the date column is in oject datatype
IPL=pd.read_csv('IPL Matches 2008-2020.csv')
IPL

In [ ]:
# Geeting the information about our dataset before changing the date datatype
IPL.info()

print("*"*50,"\n")
# Changing the datatype of our date column
IPL=pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date'])
# Geeting the information aout our dataset after applying changes
print(IPL.info())

## Convertors
To apply some transformations on our dataset even before you have loaded the dataset we use ``` converoters={'COLUMN_NAME': FUNCTION_NAME}``` and pass dictionary as value.

In [ ]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [ ]:
pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename})

## na_values parameter
Some dataset containing `NaN` values which are easier to deal, But some dataset contain placeholder insted of NaN then we use ```na_values``` and pass the list of those placeholders.

In [ ]:
# Normal Dataset
pd.read_csv('aug_train.csv')

In [ ]:
#Converting all male to NaN values
pd.read_csv('aug_train.csv',na_values=['Male',])

##  Loading a huge dataset in chunks
For dealing with those dataset having higher number of rows and our machine is not able to deal with it then we can divide our dataset into chunks. And we can perforn any task using for loop.

In [ ]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

# Working with JSON / SQL
JSON stand for Java Script Object Notation.  
SQL stand for Structured Query Language.  

Panda Documentation link: [Pd.read_json](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)

## Working with JSON
Similar to CSV file `pd.read_json` have various parameters to deal with different dataset.

In [ ]:
Recipie = pd.read_json('Recipe_train.json')
Recipie

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
# Geeting the Json data from an API
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.0426
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.8040
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.9800
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,4.4600
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,1.1900
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,2.8100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.2060
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.2670
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.3110

## Working with SQL