# Initial setups

In [ ]:
import numpy as np
import pandas as pd
import requests

In [ ]:
# prompt: generate the code to change the current working directory to main directory

import os
# Check the current working directory
print(os.getcwd())

# List contents of the main directory (root directory)
!ls

# Change the current working directory
os.chdir('/content/drive/MyDrive/Complete Machine Learning/Gathering the Data') # Write the current working directory as parameter

/content
drive  sample_data

# Working with JSON / SQL
JSON stand for Java Script Object Notation.  
SQL stand for Structured Query Language.  

Panda Documentation link: [Pd.read_json](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)  
Panda Documentation Link: [pd.read_sql_query](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html)

## Working with JSON
Similar to CSV file `pd.read_json` have various parameters to deal with different dataset.

In [ ]:
Recipie = pd.read_json('Recipe_train.json')
Recipie

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
# Geeting the Json data from an API
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.0426
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.8040
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.9800
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,4.4600
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,1.1900
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,2.8100
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.2060
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.2670
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-07-20,1752969601,0.3110

## Working with SQL
To work with database we generally recieve data in SQL format. And we have to make the connection between python and SQL using:
```
!pip install mysql.connector

import mysql.connector

connection = mysql. connector. connect(host='localhost', user='root', password='',database='DATABASE_NAME')

pd.read_sql_query("SQL_QUERY", connection)
```
>connection variable contain MySQL connection object.

The main code to acess the data is `pd.read_sql_query()` But the connection of database and python must be done by any method.

# Working with API
API (Application programming interface): An API is the set of rules that allow different software or system to talk to each other and share data without acessing the main database.  
Procedure as follow:
* Get the API link
* Generate the API_KEY after Login to site
* Using some set of code acess the data from API

## Set of codes for API
```
inport pandas as pd
import requests
```
**Requests** library is for creating HTPP request using python.
```
# General function for API
request = requests.get() # To fetch the data & API link is the argument of it
request.json() # To explicitly convert incoming data to json format
pd.DataFrame(request.json()) # To convert the data into dataframe
````

In [ ]:
# Create an empty dataframe
# Adding new data while ignoring new index
# Use for data fetching using API form various API link of same database

df = pd.DataFrame() # Create an Empty dataFrame
print("Before Appending")
display(df)

# Creating temp DataFrame and adding it to existing Dataframe
tempdf = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df = pd.concat([df, tempdf], ignore_index=True) # To append the data into dataframe

print("After Appending")
display(df)

Before Appending

Empty DataFrame
Columns: []
Index: []

After Appending

   col1  col2
0     1     3
1     2     4

In [ ]:
import requests

url = "https://imdb-top-1000-movies-series.p.rapidapi.com/list/1"

headers = {
	"x-rapidapi-key": "c56f66a780msh7bdfd915cb5c41ep16bd5fjsnabfdbf9f7c08",
	"x-rapidapi-host": "imdb-top-1000-movies-series.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'message': 'You are not subscribed to this API.'}

# Working with Web scraping