# Initial setups

In [ ]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
# prompt: generate the code to change the current working directory to main directory

import os
# Check the current working directory
print(os.getcwd())

# List contents of the main directory (root directory)
!ls

# Change the current working directory
os.chdir('/content/drive/MyDrive/Complete Machine Learning') # Write the current working directory as parameter

/content
drive  sample_data

## Apending (Ignoring index)

In [ ]:
# Concept of ignoring index in apending
# Used for data fetching using API form various API link of same database

df = pd.DataFrame() # Create an Empty dataFrame
df1 = pd.DataFrame() # Create an Empty dataFrame
tempdf = pd.DataFrame({'col1': [1, 2], 'col2': ["Hello", "World"]}) # Adding the basic content in Dataframe
df = pd.concat([df, tempdf], ignore_index=True) # append the data into dataframe
print("Before Appending")
display(df)

tempdf = pd.DataFrame({'col1': [3, 4], 'col2': ["Toshak", "Here"]})
df1 = pd.concat([df, tempdf]) # append the data into dataframe Without ignoring the index
df = pd.concat([df, tempdf], ignore_index=True) # append the data into dataframe ignoring the index

print("\nAfter Appending")
display(df)
print("\nAfter Appending Without ignoring the index")
display(df1)

Before Appending

   col1   col2
0     1  Hello
1     2  World

After Appending

   col1    col2
0     1   Hello
1     2   World
2     3  Toshak
3     4    Here

After Appending Without ignoring the index

   col1    col2
0     1   Hello
1     2   World
0     3  Toshak
1     4    Here

# Working with API
API (Application programming interface): An API is the set of rules that allow different software or system to talk to each other and share data without acessing the main database.  
Procedure as follow:
* Get the API link
* Generate the API_KEY after Login to site
* Using some set of code acess the data from API

## Set of codes for API of TMDB Website for Movie dataset
```
inport pandas as pd
import requests
```
**Requests** library is for creating HTPP request using python.
```
# General function for API
request = requests.get() # To fetch the data & API link is the argument of it
request.json() # To explicitly convert incoming data to json format
pd.DataFrame(request.json()) # To convert the data into dataframe
````

In [ ]:
requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=0818b5f3bd67ed234329d4b90d2d3550&language=en-US&page=1")

In [ ]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=0818b5f3bd67ed234329d4b90d2d3550&language=en-US&page=1")
response.json() #To explicitly convert into json format
response.json()['results'] # As the data of movie is stored in results
pd.DataFrame(response.json()['results']).head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,27.0587,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.712,29019
1,False,/jdHsptJbtalEuVhCV5i7kSC3g0x.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",31.5682,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.686,21932
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,14.7592,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13251
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,14.5840,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,16770
4,False,/bxgTSUenZDHNFerQ1whRKplrMKF.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,13.8523,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.549,9459

In [ ]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.0587,8.712,29019
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,31.5682,8.686,21932
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,14.7592,8.572,13251
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,14.5840,8.567,16770
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,13.8523,8.549,9459

In [ ]:
Movie_df = pd.DataFrame()
for i in range (1,501):
  response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=0818b5f3bd67ed234329d4b90d2d3550&language=en-US&page={}".format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  Movie_df = pd.concat([Movie_df, temp_df], ignore_index=True)

In [ ]:
Movie_df.head()
Movie_df.shape
Movie_df.to_csv('Gathering the Data/Movie_df.csv')

# Working with Web scraping

1) Checking for website responce: `requests.get("URL")`
2) Creating Object to acess methods of BeautifulSoup class:
```
Webpage = requests.get("URL").text
Soup = BeautifulSoup(Webpage, 'lxml')
```

If the responce is **<Response [403]>** then :-
```
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
requests.get('url',headers=headers)
```

Basic attributes of class (BeautifulSoup) :-
```
Soup.find_all("h3") # To get the list of all h3 tags
display(len(Soup.find_all("h3"))) # To get the total no of h3 tags used
print(Soup.find_all("h3")[5].text)
```

In [ ]:
Webpage = requests.get("https://engineering.careers360.com/colleges/ranking?page=1&icn=engineering-ranking_landing-page&ici=data-section_c360-home&sort_by=1").text
Soup = BeautifulSoup(Webpage, 'lxml') # Creating Object to acess methods of class = BeautifulSoup

In [ ]:
Soup.find_all("h3") # To get the list of all h3 tags
display(len(Soup.find_all("h3"))) # To get the total no of h3 tags used
print(Soup.find_all("h3")[5].text)

69

Comparison of Top Engineering Colleges

## Collecting the data of 1300 College usign Web-sraping on careers360 website
<img src="https://drive.google.com/uc?id=1dVblK892ad991n5sUeKPEtWI2026EDy9" alt="Card_block" width="1000">

From all such card_block fetching information like:
* IIT Madras (IITM)
* AAAAA
* Public/Government
* 4.7/5
* 127 Reviews

Used logic:
```
Colleges[0].find('h3', class_="college_name_heading").text
Colleges[0].find_all('span')[1].find_all('p', class_="college-rank-rating")[1].text
Colleges[0].find_all('span')[3].find('p', class_="college-rank-rating").text
Colleges[0].find_all('span')[5].find('p', class_="college-rank-rating").text
Colleges[0].find_all('span')[5].find('a').text
```

In [ ]:
Webpage = requests.get("https://engineering.careers360.com/colleges/ranking?page=1&icn=engineering-ranking_landing-page&ici=data-section_c360-home&sort_by=1").text
Soup = BeautifulSoup(Webpage, 'lxml') # Creating Object to acess methods of class = BeautifulSoup

# Creating list of all card_blocks to fetch data in easier way
Colleges = Soup.find_all("div", class_= 'card_block')
len(Colleges)

50

In [ ]:
# Append and display length of all the data of each 50 colleges

Name = []       # IIT Madras (IITM)
C_Rating = []   # AAAAA
Ownership = []  # Public/Government
Rating = []     # 4.7/5
Reviews = []    # 127 Reviews

for i in Colleges:
  Name.append(i.find('h3', class_="college_name_heading").text)
  C_Rating.append(i.find_all('span')[1].find_all('p', class_="college-rank-rating")[1].text)
  Ownership.append(i.find_all('span')[3].find('p', class_="college-rank-rating").text)
  Rating.append(i.find_all('span')[5].find('p', class_="college-rank-rating").text)
  Reviews.append(i.find_all('span')[5].find('a').text)

dist = {'Name': Name, 'C_Rating': C_Rating, 'Ownership': Ownership, 'Rating': Rating, 'Reviews': Reviews}
df = pd.DataFrame(dist)
df.head()
df.shape

(50, 5)

In [ ]:
# Combining all code in one cell and fetching data from all pages
# There are 26 pages and each pages have 50 colleges
# Final dataset have shape (1300,5)
Final = pd.DataFrame()

for j in range(1,27):# Traverse through each 26 pages
  URL = "https://engineering.careers360.com/colleges/ranking?page={}&icn=engineering-ranking_landing-page&ici=data-section_c360-home&sort_by=1".format(j)
  Request = requests.get(URL).text
  Soup = BeautifulSoup(Webpage, 'lxml') # Creating Object to acess methods of class = BeautifulSoup

  Colleges = Soup.find_all("div", class_= 'card_block') # Creating list of all card_blocks to fetch data in easier way

  # Appending data of each colleges
  Name = []       # IIT Madras (IITM)
  C_Rating = []   # AAAAA
  Ownership = []  # Public/Government
  Rating = []     # 4.7/5
  Reviews = []    # 127 Reviews

  for i in Colleges:
    Name.append(i.find('h3', class_="college_name_heading").text)
    C_Rating.append(i.find_all('span')[1].find_all('p', class_="college-rank-rating")[1].text)
    Ownership.append(i.find_all('span')[3].find('p', class_="college-rank-rating").text)
    Rating.append(i.find_all('span')[5].find('p', class_="college-rank-rating").text)
    Reviews.append(i.find_all('span')[5].find('a').text)

  #Creating and Converting dictionary to Final DataFrame
  dist = {'Name': Name, 'C_Rating': C_Rating, 'Ownership': Ownership, 'Rating': Rating, 'Reviews': Reviews}
  df = pd.DataFrame(dist)
  Final = pd.concat([Final, df], ignore_index=True) #Ignoring index

#Printing the size of College_DataFrame
Final.shape
Final.to_csv('Gathering the Data/College_Data.csv')