# Initial setups

In [1]:
import numpy as np
import pandas as pd

In [2]:
# prompt: generate the code to change the current working directory to main directory

import os
# Check the current working directory
print(os.getcwd())

# Change the current working directory
os.chdir('/content/drive/MyDrive/Complete Machine Learning') # Write the current working directory as parameter

# List contents of the main directory (root directory)
!ls

/content
 Data		 'Data Preprocessing'   Numpy.ipynb
'Data Analysis'  'Gathering the Data'  'Python introduction.ipynb'

In [3]:
AB_NYC = pd.read_csv('Data/AB_NYC_2019.csv')

# Correcting DataType
AB_NYC["id"] = AB_NYC["id"].astype(str)
AB_NYC["host_id"] = AB_NYC["host_id"].astype(str)
AB_NYC["latitude"] = AB_NYC["latitude"].astype(str)
AB_NYC["longitude"] = AB_NYC["longitude"].astype(str)

# Null Values & Duplicates
# AB_NYC = AB_NYC.drop_duplicates(keep='last',ignore_index=True)
# AB_NYC = AB_NYC.dropna()

# Univariate Analysis (Non Graphical)
Univariate analysis involves the examination of a single variable in isolation. It allows us to gain insights into the distribution, central tendency, and variability of that variable.

In [4]:
display(AB_NYC.head())
display(AB_NYC.info())

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.9419,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48906 entries, 0 to 48905
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48906 non-null  object
 1   name                            48890 non-null  object
 2   host_id                         48906 non-null  object
 3   host_name                       48885 non-null  object
 4   neighbourhood_group             48906 non-null  object
 5   neighbourhood                   48906 non-null  object
 6   latitude                        48906 non-null  object
 7   longitude                       48906 non-null  object
 8   room_type                       48906 non-null  object
 9   price                           48906 non-null  int64
 10  minimum_nights                  48906 non-null  int64
 11  number_of_reviews               48906 non-null  int64
 12  last_review                     38854 non-null  object
 13  reviews_per_month               38854 non-null  float64
 14  calculated_host_listings_count  48906 non-null  int64
 15  availability_365                48906 non-null  int64
dtypes: float64(1), int64(5), object(10)
memory usage: 6.0+ MB

None

## 1. Mathematical Summary of Data
The `describe()` function gives an overview of the numerical columns in the dataset as follows:  
* **count:** Number of non-null values.  
* **mean:** The average value of the column.  
* **std:** Standard deviation, which tells us how spread out the data is.  
* **min:** The minimum value.  
* **25%, 50%, 75%:** The quartiles (percentiles) of the data.
* **max:** The highest value in the column.

In [5]:
AB_NYC.describe()

,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,48906.000000,48906.000000,48906.000000,38854.000000,48906.000000,48906.000000
mean,152.711324,7.031612,23.300454,1.373151,7.142702,112.782031
std,240.128713,20.512489,44.607175,1.680270,32.948926,131.620370
min,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

## 2. Analyzing Categorical Data
To understand categorical variables, we can use the `df.nunique()` function to count unique values. And `df['COLUMN_NAME'].value_counts()`to count occurrences of each category.

```
pd.value_counts(normalize: bool=False, sort: bool=True, ascending: bool=False, bins=None)
```
> Normalize →  (default = False) (optional) If True then return relative

In [6]:
AB_NYC.nunique()

id                                48895
name                              47896
host_id                           37457
host_name                         11452
neighbourhood_group                   5
neighbourhood                       221
latitude                          19048
longitude                         14718
room_type                             3
price                               674
minimum_nights                      109
number_of_reviews                   394
last_review                        1764
reviews_per_month                   937
calculated_host_listings_count       47
availability_365                    366
dtype: int64

In [7]:
display(AB_NYC['neighbourhood_group'].value_counts())
display(AB_NYC['neighbourhood_group'].value_counts(normalize=True))

neighbourhood_group
Manhattan        21669
Brooklyn         20107
Queens            5666
Bronx             1091
Staten Island      373
Name: count, dtype: int64

neighbourhood_group
Manhattan        0.443074
Brooklyn         0.411136
Queens           0.115855
Bronx            0.022308
Staten Island    0.007627
Name: proportion, dtype: float64

In [8]:
display(AB_NYC["room_type"].value_counts())
display(AB_NYC["room_type"].value_counts(normalize=True))

room_type
Entire home/apt    25414
Private room       22332
Shared room         1160
Name: count, dtype: int64

room_type
Entire home/apt    0.519650
Private room       0.456631
Shared room        0.023719
Name: proportion, dtype: float64

## 3. Analyzing Numerical Data by category
To analyze numerical data using categories, we use binning. Binning allows you to segment the data into meaningful intervals, making it easier to identify age groups, or to analyze patterns within specific ranges.

Syntax:
```
pd.value_counts(normalize: bool=False, sort: bool=True, ascending: bool=False, bins=None)
```
> Normalize →  (default = False) (optional) If True then return relative frequencies of the unique values. (Percentage)  
> sort →  (default = True) (optional) Sorts results by counts if True.  
> ascending →  (default = False) (optional) If True, sorts smallest to largest.  
> bins → (default = None) (optional) Groups values into intervals (for numerical data).  
> dropna → (default = True) (optional) Ignores NaN values if True.

`bins=n` : This divides the column into `n` equal bins and counts occurrences in each range.  
We can define custom bins using `bins = [-10, 0, 50, 100...]` and `bins = bins`.

In [9]:
AB_NYC["price"].value_counts(bins=5)

(-10.001, 2000.0]    48820
(2000.0, 4000.0]        54
(4000.0, 6000.0]        16
(6000.0, 8000.0]         9
(8000.0, 10000.0]        7
Name: count, dtype: int64

In [10]:
bins = [-10, 0, 50, 100, 200, 500, 800, 2000, 4000, 10000]
AB_NYC["price"].value_counts(bins=bins, sort= False)

(-10.001, 0.0]          11
(0.0, 50.0]           6550
(50.0, 100.0]        17373
(100.0, 200.0]       16588
(200.0, 500.0]        7340
(500.0, 800.0]         624
(800.0, 2000.0]        334
(2000.0, 4000.0]        54
(4000.0, 10000.0]       32
Name: count, dtype: int64

## 4. Measures of Central Tendency
It help identify a single value that best represents the center of a dataset. They give an overall idea of where most data points lie and are useful for summarizing and comparing datasets.

* **Mean** – The average of all values; shows the dataset’s overall balance point.  
Syntax: `df['COLUMN_NAME'].mean()`  

* **Median** – The middle value when data is sorted; less affected by outliers.  
Syntax: `df['COLUMN_NAME'].median()`  

* **Standard Deviation** – Measures how spread out the data is from the mean.  
Syntax: `df['COLUMN_NAME'].std()`

* **Skewness** – Shows whether the data leans left, right, or is symmetric.  
Syntax: `df['COLUMN_NAME'].skew()`

* **Kurtosis** – Indicates whether the data has heavy or light tails compared to a normal curve.  
Syntax: `df['COLUMN_NAME'].kurt()`

In [11]:
mean = AB_NYC["price"].mean()
median = AB_NYC["price"].median()
std = AB_NYC["price"].std()
skew = AB_NYC["price"].skew()
kurt = AB_NYC["price"].kurt()
print(f"Mean:", mean,
      "\nMedian:", median,
      "\nStandard Deviation:", std,
      "\nSkewness:", skew,
      "\nKurtosis:", kurt
      )

Mean: 152.71132376395533
Median: 106.0
Standard Deviation: 240.1287131622437
Skewness: 19.120831694826197
Kurtosis: 585.7930484394186

## 5. Correlation Analysis
Correlation helps determine if two numerical variables are related.

**Correlation:** Correlation is a statistical measure that quantifies the degree of association or relationship between two variables. It is typically used for bivariate analysis but can also be relevant in univariate analysis to explore potential relationships that might exist between different subsets or aspects of a single variable.  
`df.corr()` returns a correlation matrix in the form of a new DataFrame. Where:
* Rows and columns represent the numerical columns of the original DataFrame.
* Values are the correlation coefficients between each pair of columns.
* The diagonal values are always 1.0 (each column perfectly correlates with itself).

In [12]:
AB_NYC.corr(numeric_only=True)

,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
price,1.000000,0.042771,-0.048014,-0.030608,0.057478,0.081817
minimum_nights,0.042771,1.000000,-0.080093,-0.121772,0.127917,0.144146
number_of_reviews,-0.048014,-0.080093,1.000000,0.549291,-0.072375,0.172002
reviews_per_month,-0.030608,-0.121772,0.549291,1.000000,-0.009414,0.185818
calculated_host_listings_count,0.057478,0.127917,-0.072375,-0.009414,1.000000,0.225680
availability_365,0.081817,0.144146,0.172002,0.185818,0.225680,1.000000